#!/bin/zsh
# Rename physical files using ZSH (supports associative arrays)
set -e
TS_DIR="/Users/admin/Documents/Code/UltimateDecompression/assets/scripts"

echo "=== Renaming physical files ==="

typeset -A RENAMES
RENAMES=(
"$TS_DIR/Main.ts" "$TS_DIR/UdAppEntry.ts"
"$TS_DIR/core/manager/UIMgr.ts" "$TS_DIR/core/manager/UdPanelHub.ts"
"$TS_DIR/core/popMessage/PopMgr.ts" "$TS_DIR/core/popMessage/UdToastHub.ts"
"$TS_DIR/core/popMessage/BasePopView.ts" "$TS_DIR/core/popMessage/UdToastBase.ts"
"$TS_DIR/core/popMessage/IPopRewardMsg.ts" "$TS_DIR/core/popMessage/IUdRewardItem.ts"
"$TS_DIR/core/popMessage/PopMsgColors.ts" "$TS_DIR/core/popMessage/UdToastColors.ts"
"$TS_DIR/core/view/compoment/BaseView.ts" "$TS_DIR/core/view/compoment/UdFullView.ts"
"$TS_DIR/core/view/compoment/SubView.ts" "$TS_DIR/core/view/compoment/UdSubPanel.ts"
"$TS_DIR/core/view/compoment/EventSubView.ts" "$TS_DIR/core/view/compoment/UdEventPanel.ts"
"$TS_DIR/core/view/med/ModuleViewEnums.ts" "$TS_DIR/core/view/med/UdModuleKind.ts"
"$TS_DIR/core/view/med/ModuleViews.ts" "$TS_DIR/core/view/med/UdModuleMap.ts"
"$TS_DIR/core/utils/PathUtils.ts" "$TS_DIR/core/utils/UdFilePathKit.ts"
"$TS_DIR/core/utils/ResPathUtils.ts" "$TS_DIR/core/utils/UdAssetPathKit.ts"
"$TS_DIR/extension/basecore/Dictionary.ts" "$TS_DIR/extension/basecore/UdKeyMap.ts"
"$TS_DIR/extension/basecore/List.ts" "$TS_DIR/extension/basecore/UdSeqList.ts"
"$TS_DIR/extension/basecore/ListSortUtils.ts" "$TS_DIR/extension/basecore/UdSeqSorter.ts"
"$TS_DIR/extension/basecore/Mathf.ts" "$TS_DIR/extension/basecore/UdMathKit.ts"
"$TS_DIR/extension/basecore/RefDecorator.ts" "$TS_DIR/extension/basecore/UdDecoratorKit.ts"
"$TS_DIR/extension/basecore/SortType.ts" "$TS_DIR/extension/basecore/UdSortDir.ts"
"$TS_DIR/extension/view/BaseUIMgr.ts" "$TS_DIR/extension/view/UdPanelHubCore.ts"
"$TS_DIR/extension/view/compoment/View.ts" "$TS_DIR/extension/view/compoment/UdViewCore.ts"
"$TS_DIR/extension/view/compoment/ResBase.ts" "$TS_DIR/extension/view/compoment/UdResFinder.ts"
"$TS_DIR/extension/view/types/UILayerType.ts" "$TS_DIR/extension/view/types/UdLayerKind.ts"
"$TS_DIR/extension/view/types/UIEventType.ts" "$TS_DIR/extension/view/types/UdPanelSignal.ts"
"$TS_DIR/extension/view/types/EaseType.ts" "$TS_DIR/extension/view/types/UdEaseKind.ts"
"$TS_DIR/extension/view/utils/EaseUtils.ts" "$TS_DIR/extension/view/utils/UdEaseKit.ts"
"$TS_DIR/extension/view/animations/ViewAnimation.ts" "$TS_DIR/extension/view/animations/UdViewMotion.ts"
"$TS_DIR/extension/eventListener/Listener.ts" "$TS_DIR/extension/eventListener/UdSignalBus.ts"
"$TS_DIR/extension/eventListener/ComponentListener.ts" "$TS_DIR/extension/eventListener/UdNodeSignal.ts"
"$TS_DIR/extension/eventListener/IListener.ts" "$TS_DIR/extension/eventListener/IUdSignalBus.ts"
"$TS_DIR/extension/eventListener/ListenerHandlerVo.ts" "$TS_DIR/extension/eventListener/UdSignalSlot.ts"
"$TS_DIR/extension/resources/CCAsset.ts" "$TS_DIR/extension/resources/UdAssetItem.ts"
"$TS_DIR/extension/resources/LoadTask.ts" "$TS_DIR/extension/resources/UdLoadRequest.ts"
"$TS_DIR/extension/resources/ResourceEventType.ts" "$TS_DIR/extension/resources/UdResSignal.ts"
"$TS_DIR/extension/resources/ResourceLoadPriority.ts" "$TS_DIR/extension/resources/UdLoadTier.ts"
"$TS_DIR/extension/resources/ResourceLoader.ts" "$TS_DIR/extension/resources/UdLoadRunner.ts"
"$TS_DIR/extension/resources/ResourceManager.ts" "$TS_DIR/extension/resources/UdResHub.ts"
"$TS_DIR/extension/time/TimeMgr.ts" "$TS_DIR/extension/time/UdTimerHub.ts"
"$TS_DIR/extension/time/TimerData.ts" "$TS_DIR/extension/time/UdTimerSlot.ts"
"$TS_DIR/extension/update/UpdateMgr.ts" "$TS_DIR/extension/update/UdTickHub.ts"
"$TS_DIR/extension/update/IUpdate.ts" "$TS_DIR/extension/update/IUdTickable.ts"
"$TS_DIR/extension/utils/ClassUtils.ts" "$TS_DIR/extension/utils/UdReflectKit.ts"
"$TS_DIR/extension/utils/NodeUtils.ts" "$TS_DIR/extension/utils/UdNodeKit.ts"
"$TS_DIR/extension/utils/RandomUtils.ts" "$TS_DIR/extension/utils/UdRandomKit.ts"
"$TS_DIR/extension/utils/DateUtils.ts" "$TS_DIR/extension/utils/UdDateKit.ts"
"$TS_DIR/extension/utils/DeviceUtils.ts" "$TS_DIR/extension/utils/UdDeviceKit.ts"
"$TS_DIR/extension/utils/EnumUtils.ts" "$TS_DIR/extension/utils/UdEnumKit.ts"
"$TS_DIR/extension/utils/LoadUtils.ts" "$TS_DIR/extension/utils/UdPathKit.ts"
"$TS_DIR/extension/pool/PoolMgr.ts" "$TS_DIR/extension/pool/UdObjCache.ts"
"$TS_DIR/extension/pool/IPoolInstance.ts" "$TS_DIR/extension/pool/IUdReusable.ts"
"$TS_DIR/extension/game/GameButton.ts" "$TS_DIR/extension/game/UdButton.ts"
"$TS_DIR/extension/game/GameLabel.ts" "$TS_DIR/extension/game/UdLabel.ts"
"$TS_DIR/extension/game/GameSprite.ts" "$TS_DIR/extension/game/UdSprite.ts"
"$TS_DIR/extension/game/GameSpine.ts" "$TS_DIR/extension/game/UdSpine.ts"
"$TS_DIR/extension/components/BaseComponent.ts" "$TS_DIR/extension/components/UdBehavior.ts"
"$TS_DIR/extension/components/GrayEffect.ts" "$TS_DIR/extension/components/UdGrayMask.ts"
"$TS_DIR/extension/components/GameBtn/BtnEventType.ts" "$TS_DIR/extension/components/GameBtn/UdBtnSignal.ts"
"$TS_DIR/extension/log/LogMgr.ts" "$TS_DIR/extension/log/UdLogHub.ts"
"$TS_DIR/extension/log/BaseLog.ts" "$TS_DIR/extension/log/UdLogCore.ts"
"$TS_DIR/extension/log/LogLevelType.ts" "$TS_DIR/extension/log/UdLogLevel.ts"
"$TS_DIR/extension/audio/AudioMgr.ts" "$TS_DIR/extension/audio/UdAudioHub.ts"
"$TS_DIR/extension/audio/AudioPlayer.ts" "$TS_DIR/extension/audio/UdAudioTrack.ts"
"$TS_DIR/extension/audio/AudioConfig.ts" "$TS_DIR/extension/audio/UdAudioDef.ts"
"$TS_DIR/extension/audio/AudioEventType.ts" "$TS_DIR/extension/audio/UdAudioSignal.ts"
"$TS_DIR/module/mainGame/views/MainGameView.ts" "$TS_DIR/module/mainGame/views/UdGameMain.ts"
"$TS_DIR/module/mainGame/views/MainGameResultView.ts" "$TS_DIR/module/mainGame/views/UdGameResult.ts"
"$TS_DIR/module/mainGame/items/MainGameFruitItem.ts" "$TS_DIR/module/mainGame/items/UdFruitBlock.ts"
"$TS_DIR/module/popMessage/PopMsgView.ts" "$TS_DIR/module/popMessage/UdToastView.ts"
"$TS_DIR/module/popMessage/PopMsgSubView.ts" "$TS_DIR/module/popMessage/UdToastItem.ts"
"$TS_DIR/module/popMessage/types/PopViewEventType.ts" "$TS_DIR/module/popMessage/types/UdToastSignal.ts"
)

for old new in "${(@kv)RENAMES}"; do
    if [[ -f "$old" ]]; then
        echo "  mv $(basename $old) -> $(basename $new)"
        mv "$old" "$new"
    fi
done

echo "File renames complete."
